# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b513602d9821a307a571f9a7a64746bb5fe309a80c6e3a925beb6e229871a3a3c729bfdca92224414d75a76199b5e2420fd453229f91415dc8364aa71aaf03

test:
  secret_key_base: e1cf4452efefd09ebe322248e9fc7462bfa76ce345ed11ab87d01d939bbb28ee5bc0ca412d742f342c93d1eb436d83cdfd1cfbce539af3d07932b2a244ad84fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
